# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/corentin/Documents/Switch-Test/SwitchListener

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/corentin/Documents/Switch-Test/SwitchListener

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corentin/Documents/Switch-Test/SwitchListener/CMakeFiles /home/corentin/Documents/Switch-Test/SwitchListener/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/corentin/Documents/Switch-Test/SwitchListener/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SwitchListener

# Build rule for target.
SwitchListener: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SwitchListener
.PHONY : SwitchListener

# fast build rule for target.
SwitchListener/fast:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/build
.PHONY : SwitchListener/fast

#=============================================================================
# Target rules for targets named ListHIDDevice

# Build rule for target.
ListHIDDevice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ListHIDDevice
.PHONY : ListHIDDevice

# fast build rule for target.
ListHIDDevice/fast:
	$(MAKE) -f tools/CMakeFiles/ListHIDDevice.dir/build.make tools/CMakeFiles/ListHIDDevice.dir/build
.PHONY : ListHIDDevice/fast

src/AnswerReader.o: src/AnswerReader.cpp.o

.PHONY : src/AnswerReader.o

# target to build an object file
src/AnswerReader.cpp.o:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/AnswerReader.cpp.o
.PHONY : src/AnswerReader.cpp.o

src/AnswerReader.i: src/AnswerReader.cpp.i

.PHONY : src/AnswerReader.i

# target to preprocess a source file
src/AnswerReader.cpp.i:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/AnswerReader.cpp.i
.PHONY : src/AnswerReader.cpp.i

src/AnswerReader.s: src/AnswerReader.cpp.s

.PHONY : src/AnswerReader.s

# target to generate assembly for a file
src/AnswerReader.cpp.s:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/AnswerReader.cpp.s
.PHONY : src/AnswerReader.cpp.s

src/Controller.o: src/Controller.cpp.o

.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i

.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s

.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/HidComm.o: src/HidComm.cpp.o

.PHONY : src/HidComm.o

# target to build an object file
src/HidComm.cpp.o:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidComm.cpp.o
.PHONY : src/HidComm.cpp.o

src/HidComm.i: src/HidComm.cpp.i

.PHONY : src/HidComm.i

# target to preprocess a source file
src/HidComm.cpp.i:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidComm.cpp.i
.PHONY : src/HidComm.cpp.i

src/HidComm.s: src/HidComm.cpp.s

.PHONY : src/HidComm.s

# target to generate assembly for a file
src/HidComm.cpp.s:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidComm.cpp.s
.PHONY : src/HidComm.cpp.s

src/HidScanner.o: src/HidScanner.cpp.o

.PHONY : src/HidScanner.o

# target to build an object file
src/HidScanner.cpp.o:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidScanner.cpp.o
.PHONY : src/HidScanner.cpp.o

src/HidScanner.i: src/HidScanner.cpp.i

.PHONY : src/HidScanner.i

# target to preprocess a source file
src/HidScanner.cpp.i:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidScanner.cpp.i
.PHONY : src/HidScanner.cpp.i

src/HidScanner.s: src/HidScanner.cpp.s

.PHONY : src/HidScanner.s

# target to generate assembly for a file
src/HidScanner.cpp.s:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/HidScanner.cpp.s
.PHONY : src/HidScanner.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SwitchListener.dir/build.make CMakeFiles/SwitchListener.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SwitchListener"
	@echo "... edit_cache"
	@echo "... ListHIDDevice"
	@echo "... src/AnswerReader.o"
	@echo "... src/AnswerReader.i"
	@echo "... src/AnswerReader.s"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/HidComm.o"
	@echo "... src/HidComm.i"
	@echo "... src/HidComm.s"
	@echo "... src/HidScanner.o"
	@echo "... src/HidScanner.i"
	@echo "... src/HidScanner.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

